import { useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { FiHeart, FiStar, FiMapPin, FiChevronLeft, FiChevronRight } from 'react-icons/fi'
import { FaHeart } from 'react-icons/fa'
import { useAuth } from '../../context/AuthContext'
import { wishlistService } from '../../services/services'
import { useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'

export default function PropertyCard({ property, index = 0, compact = true }) {
  const { isAuthenticated } = useAuth(); const queryClient = useQueryClient(); const [wishlisted, setWishlisted] = useState(property.isWishlisted || false); const [imgIndex, setImgIndex] = useState(0); const [imgLoaded, setImgLoaded] = useState(false)
  const images = property.images?.length ? property.images.map(i => i.url) : [property.primaryImageUrl || 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600']
  const toggleWishlist = async e => { e.preventDefault(); e.stopPropagation(); if (!isAuthenticated) { toast.error('Please log in to save properties'); return }; try { const result = await wishlistService.toggle(property.id); setWishlisted(result.wishlisted); queryClient.invalidateQueries({ queryKey: ['wishlist'] }) } catch { toast.error('Something went wrong') } }
  const nextImg = e => { e.preventDefault(); e.stopPropagation(); setImgIndex(i => (i + 1) % images.length) }; const prevImg = e => { e.preventDefault(); e.stopPropagation(); setImgIndex(i => (i - 1 + images.length) % images.length) }
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04, duration: 0.3 }}><Link to={`/properties/${property.id}`} className="group block"><div className={`relative ${compact ? 'aspect-[1.05/1]' : 'aspect-[4/3]'} mb-3 overflow-hidden rounded-[22px]`}><div className="relative h-full w-full">{!imgLoaded && <div className="skeleton absolute inset-0" />}<img src={images[imgIndex]} alt={property.title} className={`h-full w-full object-cover transition-all duration-500 group-hover:scale-105 ${imgLoaded ? 'opacity-100' : 'opacity-0'}`} onLoad={() => setImgLoaded(true)} loading="lazy" /></div>{images.length > 1 && <><button onClick={prevImg} className="absolute left-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-white/90 opacity-0 shadow-sm transition-opacity group-hover:opacity-100"><FiChevronLeft /></button><button onClick={nextImg} className="absolute right-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-white/90 opacity-0 shadow-sm transition-opacity group-hover:opacity-100"><FiChevronRight /></button></>}<motion.button whileHover={{ scale: 1.15 }} whileTap={{ scale: .85 }} onClick={toggleWishlist} className="absolute right-4 top-4 z-10">{wishlisted ? <FaHeart className="text-2xl text-brand-pink drop-shadow-lg" /> : <FiHeart className="text-2xl text-white drop-shadow-lg" />}</motion.button>{property.averageRating >= 4.8 && <div className="absolute left-4 top-4 rounded-full border border-black/5 bg-white/95 px-3 py-1 text-xs font-semibold text-brand-dark shadow-sm">Guest favourite</div>}</div><div className="space-y-1"><div className="flex items-center justify-between gap-2"><h3 className="truncate text-[15px] font-semibold text-brand-dark">{property.title}</h3>{property.averageRating > 0 && <div className="flex shrink-0 items-center gap-1 text-sm"><FiStar className="fill-brand-dark text-[11px] text-brand-dark" /><span>{property.averageRating?.toFixed(2)}</span></div>}</div>{!compact && <><div className="flex items-center gap-1 text-sm text-brand-gray"><FiMapPin className="text-xs" /><span>{property.city}, {property.country}</span></div><p className="text-sm text-brand-gray">{property.bedrooms} beds · {property.bathrooms} baths · {property.maxGuests} guests</p></>}<p className="text-sm text-brand-gray"><span className="font-medium text-brand-dark">₹{Math.round(property.pricePerNight * 2).toLocaleString('en-IN')}</span> for 2 nights</p></div></Link></motion.div>
}
