services:
  - type: web
    name: airbnb-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://airbnb.vercel.app
    healthCheckPath: /actuator/health
