import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { FiCalendar, FiChevronLeft, FiChevronRight, FiGlobe, FiHelpCircle, FiHeart, FiHome, FiLayout, FiLogOut, FiMenu, FiMinus, FiNavigation, FiPlus, FiSearch } from 'react-icons/fi'
import { useAuth } from '../../context/AuthContext'

const destinations = [
  ['Nearby', 'Find what’s around you', FiNavigation, 'text-blue-500 bg-blue-50'], ['North Goa, Goa', 'Because your wishlist has stays in North Goa', FiHome, 'text-amber-600 bg-amber-50'], ['Lonavala, Maharashtra', 'For sights like Karla Caves', FiHome, 'text-rose-500 bg-rose-50'], ['Pune, Maharashtra', 'Near you', FiHome, 'text-gray-500 bg-gray-100'], ['South Goa, Goa', 'Popular beach destination', FiHome, 'text-green-600 bg-green-50'], ['Karjat, Maharashtra', 'Great for a weekend getaway', FiHome, 'text-orange-700 bg-orange-50'],
]
const guestTypes = [{ key: 'adults', label: 'Adults', hint: 'Ages 13 or above' }, { key: 'children', label: 'Children', hint: 'Ages 2–12' }, { key: 'infants', label: 'Infants', hint: 'Under 2' }, { key: 'pets', label: 'Pets', hint: 'Bringing a service animal?' }]
const week = ['S', 'M', 'T', 'W', 'T', 'F', 'S']

const Logo = () => <Link to="/" className="flex items-center gap-1.5 text-brand-pink"><span className="grid h-9 w-9 place-items-center rounded-[14px] border-[3px] border-current text-lg font-bold">A</span><span className="text-[28px] font-bold tracking-tight">airbnb</span></Link>
function CalendarMonth({ date }) { const year = date.getFullYear(); const month = date.getMonth(); const start = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate(); return <div className="min-w-[300px] flex-1"><h3 className="mb-6 text-center text-xl font-semibold">{date.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</h3><div className="grid grid-cols-7 gap-y-4 text-center">{week.map((day, i) => <span key={`${day}${i}`} className="text-sm text-brand-gray">{day}</span>)}{Array.from({ length: start }, (_, i) => <span key={`blank${i}`} />)}{Array.from({ length: days }, (_, i) => <button type="button" key={i} className="mx-auto grid h-9 w-9 place-items-center rounded-full text-base hover:bg-brand-light">{i + 1}</button>)}</div></div> }

export default function Navbar() {
  const { isAuthenticated, user, logout, isHost } = useAuth(); const navigate = useNavigate()
  const [activePanel, setActivePanel] = useState(null); const [menuOpen, setMenuOpen] = useState(false); const [where, setWhere] = useState(''); const [guestCounts, setGuestCounts] = useState({ adults: 0, children: 0, infants: 0, pets: 0 }); const [monthOffset, setMonthOffset] = useState(0); const controlsRef = useRef(null); const menuRef = useRef(null)
  const guestTotal = useMemo(() => Object.values(guestCounts).reduce((sum, count) => sum + count, 0), [guestCounts])
  const firstMonth = useMemo(() => new Date(2026, 6 + monthOffset, 1), [monthOffset]); const secondMonth = useMemo(() => new Date(2026, 7 + monthOffset, 1), [monthOffset])
  useEffect(() => { const close = e => { if (controlsRef.current && !controlsRef.current.contains(e.target)) setActivePanel(null); if (menuRef.current && !menuRef.current.contains(e.target)) setMenuOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const search = e => { e.preventDefault(); const p = new URLSearchParams(); if (where) p.set('city', where); if (guestTotal) p.set('guests', guestTotal); navigate(`/properties?${p}`); setActivePanel(null) }
  const selectDestination = name => { setWhere(name.split(',')[0]); setActivePanel(null) }; const changeGuest = (key, amount) => setGuestCounts(current => ({ ...current, [key]: Math.max(0, current[key] + amount) }))
  return <header className="border-b-2 border-[#eeeeee] bg-white text-brand-dark"><div className="relative mx-auto flex h-[100px] max-w-[1800px] items-center justify-between px-6 lg:px-9"><Logo /><nav className="absolute left-1/2 top-5 hidden -translate-x-1/2 items-center gap-10 md:flex"><Link to="/properties" className="flex flex-col items-center gap-1 border-b-4 border-brand-dark px-1 pb-2"><span className="text-4xl leading-none">🌍</span><span className="text-base font-medium">All</span></Link><Link to="/properties?propertyType=HOUSE" className="flex items-center gap-3 text-lg text-brand-gray"><span className="text-4xl">🏠</span>Homes</Link><Link to="/properties?propertyType=VILLA" className="flex items-center gap-3 text-lg text-brand-gray"><span className="text-4xl">🎈</span>Experiences</Link><Link to="/properties?propertyType=APARTMENT" className="flex items-center gap-3 text-lg text-brand-gray"><span className="text-4xl">🛎️</span>Services</Link></nav><div className="ml-auto flex items-center gap-3"><Link to={isHost ? '/host' : '/register?role=host'} className="hidden whitespace-nowrap text-base font-semibold sm:block">{isHost ? 'Host dashboard' : 'Become a host'}</Link><button className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-brand-light"><FiGlobe className="text-xl" /></button><div className="relative" ref={menuRef}><button onClick={() => setMenuOpen(v => !v)} className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-brand-light"><FiMenu className="text-xl" /></button><AnimatePresence>{menuOpen && <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 8 }} className="absolute right-0 top-14 z-[60] w-[332px] max-w-[calc(100vw-24px)] rounded-2xl bg-white p-7 shadow-modal"><Link to="#" className="flex items-center gap-3 border-b border-brand-border pb-5 text-lg"><FiHelpCircle /> Help Centre</Link><Link to="/register?role=host" className="block border-b border-brand-border py-4 text-lg font-medium">Become a host<span className="mt-1 block text-sm font-normal text-brand-gray">It’s easy to start hosting and earn extra income.</span></Link><Link to="#" className="block py-3 text-lg">Refer a host</Link><Link to="#" className="block border-b border-brand-border py-3 text-lg">Find a co-host</Link>{isAuthenticated ? <><Link to="/bookings" className="flex items-center gap-3 py-3 text-lg"><FiCalendar /> Trips</Link><Link to="/wishlist" className="flex items-center gap-3 py-3 text-lg"><FiHeart /> Wishlists</Link>{isHost && <Link to="/host" className="flex items-center gap-3 py-3 text-lg"><FiLayout /> Hosting dashboard</Link>}<button onClick={() => { logout(); setMenuOpen(false) }} className="flex w-full items-center gap-3 border-t border-brand-border pt-4 text-left text-lg"><FiLogOut /> Log out</button></> : <Link to="/login" className="block pt-5 text-lg">Log in or sign up</Link>}</motion.div>}</AnimatePresence></div></div></div>
    <div ref={controlsRef} className="relative mx-auto mb-10 max-w-[1060px]"><form onSubmit={search} className="flex items-center rounded-full border border-brand-border bg-[#eeeeee] p-2 shadow-sm"><button type="button" onClick={() => setActivePanel('where')} className={`min-w-0 flex-1 rounded-full px-8 py-3 text-left ${activePanel === 'where' ? 'bg-white shadow-md' : ''}`}><span className="block text-sm font-semibold">Where</span><input value={where} onClick={() => setActivePanel('where')} onChange={e => { setWhere(e.target.value); setActivePanel('where') }} className="w-full bg-transparent text-lg outline-none placeholder:text-brand-gray" placeholder="Search destinations" /></button><button type="button" onClick={() => setActivePanel('when')} className={`hidden flex-1 rounded-full px-8 py-3 text-left sm:block ${activePanel === 'when' ? 'bg-white shadow-md' : ''}`}><span className="block text-sm font-semibold">When</span><span className="text-lg text-brand-gray">Add dates</span></button><button type="button" onClick={() => setActivePanel('who')} className={`hidden flex-1 rounded-full px-8 py-3 text-left sm:block ${activePanel === 'who' ? 'bg-white shadow-md' : ''}`}><span className="block text-sm font-semibold">Who</span><span className="text-lg text-brand-gray">{guestTotal ? `${guestTotal} guest${guestTotal > 1 ? 's' : ''}` : 'Add guests'}</span></button><button className="ml-2 flex h-14 shrink-0 items-center gap-2 rounded-full bg-[#dd0b46] px-5 text-lg font-medium text-white"><FiSearch className="text-2xl" /><span className="hidden lg:inline">Search</span></button></form>
      <AnimatePresence>{activePanel === 'where' && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="absolute left-0 top-[96px] z-50 w-[530px] max-w-[calc(100vw-24px)] rounded-[28px] bg-white p-10 shadow-modal"><p className="mb-4 text-sm">Suggested destinations</p>{destinations.map(([name, hint, Icon, colour]) => <button type="button" key={name} onClick={() => selectDestination(name)} className="flex w-full items-center gap-5 py-3 text-left"><span className={`grid h-[70px] w-[70px] shrink-0 place-items-center rounded-2xl ${colour}`}><Icon className="text-3xl" /></span><span><span className="block text-lg font-medium">{name}</span><span className="block text-base text-brand-gray">{hint}</span></span></button>)}</motion.div>}{activePanel === 'who' && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="absolute right-0 top-[96px] z-50 w-[530px] max-w-[calc(100vw-24px)] rounded-[30px] bg-white px-14 py-8 shadow-modal">{guestTypes.map(({ key, label, hint }, index) => <div key={key} className={`flex items-center justify-between gap-5 py-5 ${index ? 'border-t border-brand-border' : ''}`}><div><p className="text-xl font-semibold">{label}</p><p className={`text-base ${key === 'pets' ? 'underline text-brand-gray' : 'text-brand-gray'}`}>{hint}</p></div><div className="flex shrink-0 items-center gap-5"><button type="button" disabled={!guestCounts[key]} onClick={() => changeGuest(key, -1)} className="grid h-10 w-10 place-items-center rounded-full bg-brand-light text-brand-gray disabled:opacity-40"><FiMinus /></button><span className="w-3 text-center text-lg">{guestCounts[key]}</span><button type="button" onClick={() => changeGuest(key, 1)} className="grid h-10 w-10 place-items-center rounded-full bg-brand-light"><FiPlus /></button></div></div>)}</motion.div>}{activePanel === 'when' && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="absolute left-1/2 top-[96px] z-50 w-[min(1060px,calc(100vw-24px))] -translate-x-1/2 rounded-[32px] bg-white px-12 py-9 shadow-modal"><div className="mx-auto mb-8 flex w-[390px] max-w-full rounded-full bg-[#eeeeee] p-1"><button type="button" className="flex-1 rounded-full bg-white py-2 text-lg shadow-sm">Dates</button><button type="button" className="flex-1 py-2 text-lg">Flexible</button></div><div className="mb-5 flex items-center justify-between"><button type="button" onClick={() => setMonthOffset(o => o - 1)} className="rounded-full p-2 hover:bg-brand-light"><FiChevronLeft /></button><button type="button" onClick={() => setMonthOffset(o => o + 1)} className="rounded-full p-2 hover:bg-brand-light"><FiChevronRight /></button></div><div className="flex gap-12 overflow-x-auto pb-3"><CalendarMonth date={firstMonth} /><CalendarMonth date={secondMonth} /></div></motion.div>}</AnimatePresence>
    </div></header>
}
